export const menFormData = [
  {
    code: 1,
    suspended: true,
    img: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "أحمد محمد علي",
    job: "مهندس مدني",
    description: "على خلق ودين، ملتزم بالصلاة والقرآن، طموح في عملي.",
    skinColor: "قمحي",
    qualification: "مهندس",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 30,
    socialStatus: "أعزب",
    height: 175,
    governorate: "القاهرة",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01098765432",
    housing: "تمليك",
    region: "متوسطة",
    brideQualification: "مؤهل عالي",
    brideAgeRange: { from: 20, to: 28 },
    brideMaritalStatus: ["أعزب", "مطلقة بدون أطفال"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تخاف الله ومحافظة على صلاتها.",
    additionalNotes: "أن تكون هادئة الطباع وتحب الحياة العائلية.",
  },
  {
    code: 2,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/22.jpg",
    name: "محمود حسن علي",
    job: "طبيب",
    description: "محب للخير، ذو أخلاق عالية، متواضع وبشوش.",
    skinColor: "فاتح",
    qualification: "دكتور",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 32,
    socialStatus: "أعزب",
    height: 178,
    governorate: "الإسكندرية",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01123456789",
    housing: "تمليك",
    region: "متوسطة",
    brideQualification: "مؤهل عالي",
    brideAgeRange: { from: 22, to: 30 },
    brideMaritalStatus: ["أعزب", "أرملة"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تكون من أسرة محترمة وتحب الاستقرار.",
    additionalNotes: "أن تكون ملتزمة بالصلاة والحجاب.",
  },
  {
    code: 3,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/26.jpg",
    name: "علي جمال إبراهيم",
    job: "محاسب",
    description: "اجتماعي، أعمل بجد وأسعى لتحقيق الاستقرار.",
    skinColor: "أسمر",
    qualification: "مؤهل عالي",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 28,
    socialStatus: "أعزب",
    height: 170,
    governorate: "الجيزة",
    sameGovernorate: false,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01234567890",
    housing: "إيجار",
    region: "شعبية",
    brideQualification: "دبلوم",
    brideAgeRange: { from: 22, to: 26 },
    brideMaritalStatus: ["أعزب"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تكون على خلق ودين، غير مدخنة.",
    additionalNotes: "تحب الأطفال والعائلة.",
  },
  {
    code: 4,
    suspended: true,
    img: "https://randomuser.me/api/portraits/men/4.jpg",
    name: "عبدالله يوسف محمود",
    job: "محامي",
    description: "محترم ومهذب، أحب الحوار والنقاش البناء.",
    skinColor: "فاتح",
    qualification: "مؤهل عالي",
    hasChildren: true,
    childrenNumber: 1,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 35,
    socialStatus: "مطلق",
    height: 180,
    governorate: "الدقهلية",
    sameGovernorate: true,
    acceptPolygamy: true,
    acceptDivorcedWidow: true,
    polygamyConditions: "",
    phone: "01065432123",
    housing: "تمليك",
    region: "متوسطة",
    brideQualification: "مؤهل متوسط ( ثانوية )",
    brideAgeRange: { from: 27, to: 35 },
    brideMaritalStatus: ["مطلقة", "أرملة"],
    brideChildren: ["لا مانع من وجود أطفال"],
    otherConditions: "تتقي الله وتحافظ على صلاتها.",
    additionalNotes: "أن تكون هادئة ومتفهمة.",
  },
  {
    code: 5,
    suspended: true,
    img: "https://randomuser.me/api/portraits/men/29.jpg",
    name: "يحيى عادل مصطفى",
    job: "تاجر",
    description: "محب للسفر، اجتماعي ومتفائل بالحياة.",
    skinColor: "قمحي",
    qualification: "مؤهل متوسط ( ثانوية )",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 40,
    socialStatus: "أرمل",
    height: 172,
    governorate: "سوهاج",
    sameGovernorate: false,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01567890123",
    housing: "إيجار",
    region: "متوسطة",
    brideQualification: "خريج",
    brideAgeRange: { from: 30, to: 40 },
    brideMaritalStatus: ["أرملة", "مطلقة"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "متدينة ومتحجبة.",
    additionalNotes: "تكون من بيئة محافظة ومحبة للحياة العائلية.",
  },
  {
    code: 6,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/28.jpg",
    name: "سامي عبدالعزيز فهمي",
    job: "مدرس",
    description: "محب للأطفال والتعليم، صبور وأحب تطوير نفسي باستمرار.",
    skinColor: "قمحي",
    qualification: "معلم",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 29,
    socialStatus: "أعزب",
    height: 174,
    governorate: "الشرقية",
    sameGovernorate: false,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01123456781",
    housing: "إيجار",
    region: "متوسطة",
    brideQualification: "مؤهل عالي",
    brideAgeRange: { from: 22, to: 27 },
    brideMaritalStatus: ["أعزب"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تكون متدينة وتحب التعليم والتربية.",
    additionalNotes: "مهتمة بتربية الأطفال وتحب الحياة الأسرية.",
  },
  {
    code: 7,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "عمرو محمد فتحي",
    job: "محاسب قانوني",
    description: "جدي في العمل ومحب للتنظيم، ملتزم بأداء العبادات.",
    skinColor: "فاتح",
    qualification: "مؤهل عالي",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 34,
    socialStatus: "مطلق",
    height: 180,
    governorate: "المنوفية",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01056789123",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "دبلوم",
    brideAgeRange: { from: 26, to: 32 },
    brideMaritalStatus: ["مطلقة", "أرملة"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تتقي الله وتحب الاستقرار الأسري.",
    additionalNotes: "تكون هادئة الطباع ومهتمة بالحياة الزوجية.",
  },
  {
    code: 8,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/30.jpg",
    name: "محمد عبدالرحمن صالح",
    job: "صاحب شركة",
    description: "عملي وطموح، أحلم بتوسيع أعمالي وحياتي العائلية.",
    skinColor: "أسمر",
    qualification: "مهندس",
    hasChildren: true,
    childrenNumber: 2,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 45,
    socialStatus: "أرمل",
    height: 178,
    governorate: "القاهرة",
    sameGovernorate: true,
    acceptPolygamy: true,
    acceptDivorcedWidow: true,
    polygamyConditions: "",
    phone: "01234567892",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "شهادة اعدادية",
    brideAgeRange: { from: 30, to: 45 },
    brideMaritalStatus: ["أرملة", "مطلقة"],
    brideChildren: ["لا مانع من وجود أطفال"],
    otherConditions: "تكون مستعدة لتحمل المسؤولية العائلية.",
    additionalNotes: "محبة للأطفال وتهتم بتكوين أسرة مستقرة.",
  },
  {
    code: 9,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "حسين علي إبراهيم",
    job: "مدير مبيعات",
    description: "اجتماعي ومحب للتواصل مع الآخرين، لدي طموحات كبيرة.",
    skinColor: "قمحي",
    qualification: "بدون مؤهل",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 33,
    socialStatus: "متزوج",
    height: 176,
    governorate: "الإسكندرية",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01098761234",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "شهادة ابتدائية",
    brideAgeRange: { from: 25, to: 32 },
    brideMaritalStatus: ["أعزب"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تكون من أسرة محترمة ومحبة للحياة الاجتماعية.",
    additionalNotes: "تكون واثقة من نفسها وملتزمة دينياً.",
  },
  {
    code: 10,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/31.jpg",
    name: "خالد محمود عبدالعزيز",
    job: "مدير مشروع",
    description: "ملتزم، جدي في عملي، وأحب تطوير مشاريعي الخاصة.",
    skinColor: "فاتح",
    qualification: "شهادة ابتدائية",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 37,
    socialStatus: "مطلق",
    height: 185,
    governorate: "أسيوط",
    sameGovernorate: false,
    acceptPolygamy: true,
    acceptDivorcedWidow: true,
    polygamyConditions: "",
    phone: "01112349876",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "بدون مؤهل",
    brideAgeRange: { from: 28, to: 35 },
    brideMaritalStatus: ["مطلقة", "أرملة"],
    brideChildren: ["لا مانع من وجود أطفال"],
    otherConditions: "تكون متفهمة وقادرة على إدارة الحياة العائلية.",
    additionalNotes: "محبة للحياة ومستعدة لتكوين عائلة مستقرة.",
  },
  {
    code: 11,
    suspended: true,
    img: "https://randomuser.me/api/portraits/men/11.jpg",
    name: "أمير يوسف العبد",
    job: "صاحب محل تجاري",
    description:
      "مجتهد في عملي وأطمح إلى تحقيق المزيد في حياتي المهنية والعائلية.",
    skinColor: "أشقر",
    qualification: "مؤهل متوسط ( ثانوية )",
    hasChildren: true,
    childrenNumber: 1,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 40,
    socialStatus: "أرمل",
    height: 173,
    governorate: "الغربية",
    sameGovernorate: true,
    acceptPolygamy: true,
    acceptDivorcedWidow: true,
    polygamyConditions: "",
    phone: "01234566789",
    housing: "تمليك",
    region: "متوسطة",
    brideQualification: "خريج",
    brideAgeRange: { from: 30, to: 40 },
    brideMaritalStatus: ["أرملة", "مطلقة"],
    brideChildren: ["لا مانع من وجود أطفال"],
    otherConditions: "تكون هادئة الطباع وملتزمة دينياً.",
    additionalNotes: "تهتم بالأطفال وتحب الحياة الأسرية.",
  },
  {
    code: 12,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/12.jpg",
    name: "أسامة سيد أحمد",
    job: "فني كهرباء",
    description: "أعمل بجد وأحب الاستقرار الأسري والهدوء.",
    skinColor: "أسمر",
    qualification: "دبلوم",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 36,
    socialStatus: "أعزب",
    height: 170,
    governorate: "الفيوم",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01098765421",
    housing: "إيجار",
    region: "شعبية",
    brideQualification: "بدون مؤهل",
    brideAgeRange: { from: 25, to: 35 },
    brideMaritalStatus: ["أعزب", "مطلقة"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تكون على خلق ودين.",
    additionalNotes: "تحب الاستقرار العائلي.",
  },
  {
    code: 13,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/33.jpg",
    name: "محمود سعيد علي",
    job: "محامي",
    description: "محب للعدالة والحق، أعمل في المحاماة منذ 10 سنوات.",
    skinColor: "قمحي",
    qualification: "دكتور",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 38,
    socialStatus: "مطلق",
    height: 175,
    governorate: "القاهرة",
    sameGovernorate: true,
    acceptPolygamy: true,
    acceptDivorcedWidow: true,
    polygamyConditions: "",
    phone: "01123467890",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "دكتور",
    brideAgeRange: { from: 30, to: 38 },
    brideMaritalStatus: ["أرملة", "مطلقة"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تتقي الله وتكون متفهمة وهادئة الطباع.",
    additionalNotes: "تحب الاستقرار وتكون جادة في حياتها الزوجية.",
  },
  {
    code: 14,
    suspended: true,
    img: "https://randomuser.me/api/portraits/men/34.jpg",
    name: "عبدالرحمن يوسف حسني",
    job: "مهندس ميكانيكا",
    description: "مجتهد وطموح، أحب الابتكار والعمل الجاد.",
    skinColor: "فاتح",
    qualification: "مهندس",
    hasChildren: true,
    childrenNumber: 1,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 42,
    socialStatus: "أرمل",
    height: 180,
    governorate: "الدقهلية",
    sameGovernorate: false,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01056789124",
    housing: "تمليك",
    region: "متوسطة",
    brideQualification: "مؤهل عالي",
    brideAgeRange: { from: 30, to: 40 },
    brideMaritalStatus: ["مطلقة", "أرملة"],
    brideChildren: ["لا مانع من وجود أطفال"],
    otherConditions: "تكون ملتزمة ومحبة للأبناء.",
    additionalNotes: "تكون على خلق وتحب العمل على تكوين أسرة.",
  },
  {
    code: 15,
    suspended: true,
    img: "https://randomuser.me/api/portraits/men/36.jpg",
    name: "حسن محمد عبدالحليم",
    job: "مدير شركة مقاولات",
    description:
      "جدي في العمل، ولدي شغف بتوسيع عملي والمشاركة في المشروعات الكبرى.",
    skinColor: "عنابي",
    qualification: "مهندس",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 46,
    socialStatus: "مطلق",
    height: 182,
    governorate: "الجيزة",
    sameGovernorate: true,
    acceptPolygamy: true,
    acceptDivorcedWidow: true,
    polygamyConditions: "",
    phone: "01234567894",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "مؤهل عالي",
    brideAgeRange: { from: 35, to: 45 },
    brideMaritalStatus: ["مطلقة", "أرملة"],
    brideChildren: ["لا مانع من وجود أطفال"],
    otherConditions: "تكون جادة في حياتها ومتفهمة لمسؤوليات الحياة.",
    additionalNotes: "تتقي الله وتقدر الحياة الأسرية.",
  },
  {
    code: 16,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/35.jpg",
    name: "أشرف إبراهيم منصور",
    job: "مصمم جرافيك",
    description: "مبدع وأحب الفن والابتكار، ملتزم دينياً وأبحث عن الاستقرار.",
    skinColor: "قمحي",
    qualification: "مؤهل عالي",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 32,
    socialStatus: "أعزب",
    height: 170,
    governorate: "الشرقية",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01123467891",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "خريج",
    brideAgeRange: { from: 25, to: 30 },
    brideMaritalStatus: ["أعزب"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تكون متفهمة وتحب الحياة الزوجية.",
    additionalNotes: "تكون ملتزمة ومحبة للهدوء والاستقرار.",
  },
  {
    code: 17,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/37.jpg",
    name: "خالد حمدي مصطفى",
    job: "محاسب مالي",
    description: "دقيق ومنظم، محب للرياضة وأهتم بالاستقرار الأسري.",
    skinColor: "أسمر",
    qualification: "مؤهل عالي",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 36,
    socialStatus: "أعزب",
    height: 175,
    governorate: "الفيوم",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01056781234",
    housing: "إيجار",
    region: "متوسطة",
    brideQualification: "خريج",
    brideAgeRange: { from: 28, to: 35 },
    brideMaritalStatus: ["أعزب"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تتقي الله وتحب الاستقرار الأسري.",
    additionalNotes: "تكون ودودة وتحب الحياة الزوجية.",
  },
  {
    code: 18,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/43.jpg",
    name: "مصطفى جمال عبدالرحيم",
    job: "فني شبكات",
    description: "مهتم بالتكنولوجيا، وأحب التطوير الدائم في عملي.",
    skinColor: "أبيض / ناصع البياض",
    qualification: "دبلوم",
    hasChildren: true,
    childrenNumber: 2,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 40,
    socialStatus: "مطلق",
    height: 178,
    governorate: "الغربية",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01234567897",
    housing: "تمليك",
    region: "راقية",
    brideQualification: "مؤهل متوسط ( ثانوية )",
    brideAgeRange: { from: 30, to: 40 },
    brideMaritalStatus: ["مطلقة", "أرملة"],
    brideChildren: ["لا مانع من وجود أطفال"],
    otherConditions: "تكون جادة ومستعدة لتكوين أسرة مستقرة.",
    additionalNotes: "تحب الأطفال وتهتم بالحياة الأسرية.",
  },
  {
    code: 19,
    suspended: false,
    img: "https://randomuser.me/api/portraits/men/40.jpg",
    name: "علي عبدالحكيم نصر",
    job: "فني إلكترونيات",
    description: "محب للتكنولوجيا وأعمل في الصيانة منذ سنوات.",
    skinColor: "قمحي",
    qualification: "دبلوم",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 35,
    socialStatus: "أعزب",
    height: 172,
    governorate: "سوهاج",
    sameGovernorate: true,
    acceptPolygamy: false,
    acceptDivorcedWidow: false,
    polygamyConditions: "",
    phone: "01112345678",
    housing: "إيجار",
    region: "متوسطة",
    brideQualification: "دبلوم",
    brideAgeRange: { from: 28, to: 35 },
    brideMaritalStatus: ["أعزب"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تتقي الله وتحب الحياة الزوجية.",
    additionalNotes: "تكون على خلق ومستعدة لتكوين أسرة.",
  },
  {
    code: 20,
    suspended: true,
    img: "https://randomuser.me/api/portraits/men/20.jpg",
    name: "علاء إبراهيم سالم",
    job: "سائق نقل ثقيل",
    description: "محب للعمل وأطمح لتوسيع أعمالي الخاصة.",
    skinColor: "أسمر",
    qualification: "مؤهل متوسط ( ثانوية )",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "سليم",
    prayer: true,
    age: 39,
    socialStatus: "أعزب",
    height: 176,
    governorate: "أسوان",
    sameGovernorate: true,
    acceptPolygamy: true,
    acceptDivorcedWidow: true,
    polygamyConditions: "",
    phone: "01234567898",
    housing: "إيجار",
    region: "متوسطة",
    brideQualification: "شهادة ابتدائية",
    brideAgeRange: { from: 30, to: 39 },
    brideMaritalStatus: ["أعزب"],
    brideChildren: ["بدون أطفال"],
    otherConditions: "تتقي الله وتحب الاستقرار الأسري.",
    additionalNotes: "تكون على خلق وتقدر الحياة الزوجية.",
  },
];
