export const menFormData = [
  {
    code: 1,
    suspended: true,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "أحمد محمد علي",
      job: "مهندس مدني",
      description: "على خلق ودين، ملتزم بالصلاة والقرآن، طموح في عملي.",
      skinColor: "قمحي",
      qualification: "بكالوريوس هندسة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 30,
      socialStatus: "أعزب",
      height: 175,
      location: "القاهرة",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01098765432",
    },
    brideRequirements: {
      ageRange: { from: 20, to: 28 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["أعزب", "مطلقة بدون أطفال"],
      children: ["بدون أطفال"],
      housing: "تمليك أو إيجار جديد",
      area: "راقية أو متوسطة",
      government: "القاهرة",
      otherConditions: "تخاف الله ومحافظة على صلاتها.",
      additionalNotes: "أن تكون هادئة الطباع وتحب الحياة العائلية.",
    },
  },
  {
    code: 2,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "محمود حسن علي",
      job: "طبيب",
      description: "محب للخير، ذو أخلاق عالية، متواضع وبشوش.",
      skinColor: "حنطي",
      qualification: "دكتوراه في الطب",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 32,
      socialStatus: "أعزب",
      height: 178,
      location: "الإسكندرية",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01123456789",
    },
    brideRequirements: {
      ageRange: { from: 22, to: 30 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["أعزب", "أرملة"],
      children: ["بدون أطفال"],
      housing: "تمليك",
      area: "متوسطة",
      government: "الإسكندرية",
      otherConditions: "تكون من أسرة محترمة وتحب الاستقرار.",
      additionalNotes: "أن تكون ملتزمة بالصلاة والحجاب.",
    },
  },
  {
    code: 3,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/3.jpg",
      name: "علي جمال إبراهيم",
      job: "محاسب",
      description: "اجتماعي، أعمل بجد وأسعى لتحقيق الاستقرار.",
      skinColor: "أسمر",
      qualification: "بكالوريوس تجارة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 28,
      socialStatus: "أعزب",
      height: 170,
      location: "الجيزة",
      sameGovernment: false,
      acceptPolygamy: false,
      phone: "01234567890",
    },
    brideRequirements: {
      ageRange: { from: 22, to: 26 },
      qualification: "دبلوم أو مؤهل جامعي",
      maritalStatus: ["أعزب"],
      children: ["بدون أطفال"],
      housing: "إيجار جديد",
      area: "شعبية أو متوسطة",
      government: "الجيزة",
      otherConditions: "تكون على خلق ودين، غير مدخنة.",
      additionalNotes: "تحب الأطفال والعائلة.",
    },
  },
  {
    code: 4,
    suspended: true,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/4.jpg",
      name: "عبدالله يوسف محمود",
      job: "محامي",
      description: "محترم ومهذب، أحب الحوار والنقاش البناء.",
      skinColor: "فاتح",
      qualification: "ليسانس حقوق",
      hasChildren: true,
      childrenNumber: 1,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 35,
      socialStatus: "مطلق",
      height: 180,
      location: "المنصورة",
      sameGovernment: true,
      acceptPolygamy: true,
      phone: "01065432123",
    },
    brideRequirements: {
      ageRange: { from: 27, to: 35 },
      qualification: "مؤهل متوسط أو جامعي",
      maritalStatus: ["مطلقة", "أرملة"],
      children: ["لا مانع من وجود أطفال"],
      housing: "تمليك",
      area: "راقية أو متوسطة",
      government: "المنصورة",
      otherConditions: "تتقي الله وتحافظ على صلاتها.",
      additionalNotes: "أن تكون هادئة ومتفهمة.",
    },
  },
  {
    code: 5,
    suspended: true,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "يحيى عادل مصطفى",
      job: "تاجر",
      description: "محب للسفر، اجتماعي ومتفائل بالحياة.",
      skinColor: "حنطي",
      qualification: "مؤهل متوسط",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 40,
      socialStatus: "أرمل",
      height: 172,
      location: "سوهاج",
      sameGovernment: false,
      acceptPolygamy: false,
      phone: "01567890123",
    },
    brideRequirements: {
      ageRange: { from: 30, to: 40 },
      qualification: "مؤهل متوسط أو جامعي",
      maritalStatus: ["أرملة", "مطلقة"],
      children: ["بدون أطفال"],
      housing: "إيجار جديد",
      area: "متوسطة",
      government: "سوهاج",
      otherConditions: "متدينة ومتحجبة.",
      additionalNotes: "تكون من بيئة محافظة ومحبة للحياة العائلية.",
    },
  },
  {
    code: 6,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "سامي عبدالعزيز فهمي",
      job: "مدرس",
      description: "محب للأطفال والتعليم، صبور وأحب تطوير نفسي باستمرار.",
      skinColor: "قمحي",
      qualification: "بكالوريوس تربية",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 29,
      socialStatus: "أعزب",
      height: 174,
      location: "الزقازيق",
      sameGovernment: false,
      acceptPolygamy: false,
      phone: "01123456781",
    },
    brideRequirements: {
      ageRange: { from: 22, to: 27 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["أعزب"],
      children: ["بدون أطفال"],
      housing: "إيجار جديد",
      area: "متوسطة",
      government: "الزقازيق",
      otherConditions: "تكون متدينة وتحب التعليم والتربية.",
      additionalNotes: "مهتمة بتربية الأطفال وتحب الحياة الأسرية.",
    },
  },
  {
    code: 7,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "عمرو محمد فتحي",
      job: "محاسب قانوني",
      description: "جدي في العمل ومحب للتنظيم، ملتزم بأداء العبادات.",
      skinColor: "فاتح",
      qualification: "بكالوريوس تجارة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 34,
      socialStatus: "مطلق",
      height: 180,
      location: "المنوفية",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01056789123",
    },
    brideRequirements: {
      ageRange: { from: 26, to: 32 },
      qualification: "دبلوم أو جامعي",
      maritalStatus: ["مطلقة", "أرملة"],
      children: ["بدون أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "المنوفية",
      otherConditions: "تتقي الله وتحب الاستقرار الأسري.",
      additionalNotes: "تكون هادئة الطباع ومهتمة بالحياة الزوجية.",
    },
  },
  {
    code: 8,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "محمد عبدالرحمن صالح",
      job: "صاحب شركة",
      description: "عملي وطموح، أحلم بتوسيع أعمالي وحياتي العائلية.",
      skinColor: "أسمر",
      qualification: "بكالوريوس إدارة أعمال",
      hasChildren: true,
      childrenNumber: 2,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 45,
      socialStatus: "أرمل",
      height: 178,
      location: "القاهرة",
      sameGovernment: true,
      acceptPolygamy: true,
      phone: "01234567892",
    },
    brideRequirements: {
      ageRange: { from: 30, to: 45 },
      qualification: "مؤهل متوسط أو جامعي",
      maritalStatus: ["أرملة", "مطلقة"],
      children: ["لا مانع من وجود أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "القاهرة",
      otherConditions: "تكون مستعدة لتحمل المسؤولية العائلية.",
      additionalNotes: "محبة للأطفال وتهتم بتكوين أسرة مستقرة.",
    },
  },
  {
    code: 9,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "حسين علي إبراهيم",
      job: "مدير مبيعات",
      description: "اجتماعي ومحب للتواصل مع الآخرين، لدي طموحات كبيرة.",
      skinColor: "قمحي",
      qualification: "بكالوريوس تسويق",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 33,
      socialStatus: "أعزب",
      height: 176,
      location: "الإسكندرية",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01098761234",
    },
    brideRequirements: {
      ageRange: { from: 25, to: 32 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["أعزب"],
      children: ["بدون أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "الإسكندرية",
      otherConditions: "تكون من أسرة محترمة ومحبة للحياة الاجتماعية.",
      additionalNotes: "تكون واثقة من نفسها وملتزمة دينياً.",
    },
  },
  {
    code: 10,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/10.jpg",
      name: "خالد محمود عبدالعزيز",
      job: "مدير مشروع",
      description: "ملتزم، جدي في عملي، وأحب تطوير مشاريعي الخاصة.",
      skinColor: "فاتح",
      qualification: "ماجستير إدارة أعمال",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 37,
      socialStatus: "مطلق",
      height: 185,
      location: "أسيوط",
      sameGovernment: false,
      acceptPolygamy: true,
      phone: "01112349876",
    },
    brideRequirements: {
      ageRange: { from: 28, to: 35 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["مطلقة", "أرملة"],
      children: ["لا مانع من وجود أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "أسيوط",
      otherConditions: "تكون متفهمة وقادرة على إدارة الحياة العائلية.",
      additionalNotes: "محبة للحياة ومستعدة لتكوين عائلة مستقرة.",
    },
  },
  {
    code: 11,
    suspended: true,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/11.jpg",
      name: "أمير يوسف العبد",
      job: "صاحب محل تجاري",
      description:
        "مجتهد في عملي وأطمح إلى تحقيق المزيد في حياتي المهنية والعائلية.",
      skinColor: "حنطي",
      qualification: "مؤهل متوسط",
      hasChildren: true,
      childrenNumber: 1,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 40,
      socialStatus: "أرمل",
      height: 173,
      location: "طنطا",
      sameGovernment: true,
      acceptPolygamy: true,
      phone: "01234566789",
    },
    brideRequirements: {
      ageRange: { from: 30, to: 40 },
      qualification: "مؤهل متوسط",
      maritalStatus: ["أرملة", "مطلقة"],
      children: ["لا مانع من وجود أطفال"],
      housing: "تمليك",
      area: "متوسطة",
      government: "طنطا",
      otherConditions: "تكون هادئة الطباع وملتزمة دينياً.",
      additionalNotes: "تهتم بالأطفال وتحب الحياة الأسرية.",
    },
  },
  {
    code: 12,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "أسامة سيد أحمد",
      job: "فني كهرباء",
      description: "أعمل بجد وأحب الاستقرار الأسري والهدوء.",
      skinColor: "أسمر",
      qualification: "دبلوم صنايع",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 36,
      socialStatus: "أعزب",
      height: 170,
      location: "الفيوم",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01098765421",
    },
    brideRequirements: {
      ageRange: { from: 25, to: 35 },
      qualification: "دبلوم أو مؤهل جامعي",
      maritalStatus: ["أعزب", "مطلقة"],
      children: ["بدون أطفال"],
      housing: "إيجار جديد",
      area: "شعبية",
      government: "الفيوم",
      otherConditions: "تكون على خلق ودين.",
      additionalNotes: "تحب الاستقرار العائلي.",
    },
  },
  {
    code: 13,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/13.jpg",
      name: "محمود سعيد علي",
      job: "محامي",
      description: "محب للعدالة والحق، أعمل في المحاماة منذ 10 سنوات.",
      skinColor: "قمحي",
      qualification: "ليسانس حقوق",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 38,
      socialStatus: "مطلق",
      height: 175,
      location: "القاهرة",
      sameGovernment: true,
      acceptPolygamy: true,
      phone: "01123467890",
    },
    brideRequirements: {
      ageRange: { from: 30, to: 38 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["أرملة", "مطلقة"],
      children: ["بدون أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "القاهرة",
      otherConditions: "تتقي الله وتكون متفهمة وهادئة الطباع.",
      additionalNotes: "تحب الاستقرار وتكون جادة في حياتها الزوجية.",
    },
  },
  {
    code: 14,
    suspended: true,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/14.jpg",
      name: "عبدالرحمن يوسف حسني",
      job: "مهندس ميكانيكا",
      description: "مجتهد وطموح، أحب الابتكار والعمل الجاد.",
      skinColor: "فاتح",
      qualification: "بكالوريوس هندسة",
      hasChildren: true,
      childrenNumber: 1,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 42,
      socialStatus: "أرمل",
      height: 180,
      location: "المنصورة",
      sameGovernment: false,
      acceptPolygamy: false,
      phone: "01056789124",
    },
    brideRequirements: {
      ageRange: { from: 30, to: 40 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["مطلقة", "أرملة"],
      children: ["لا مانع من وجود أطفال"],
      housing: "تمليك",
      area: "متوسطة",
      government: "المنصورة",
      otherConditions: "تكون ملتزمة ومحبة للأبناء.",
      additionalNotes: "تكون على خلق وتحب العمل على تكوين أسرة.",
    },
  },
  {
    code: 15,
    suspended: true,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/15.jpg",
      name: "حسن محمد عبدالحليم",
      job: "مدير شركة مقاولات",
      description:
        "جدي في العمل، ولدي شغف بتوسيع عملي والمشاركة في المشروعات الكبرى.",
      skinColor: "حنطي",
      qualification: "بكالوريوس هندسة مدنية",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 46,
      socialStatus: "مطلق",
      height: 182,
      location: "الجيزة",
      sameGovernment: true,
      acceptPolygamy: true,
      phone: "01234567894",
    },
    brideRequirements: {
      ageRange: { from: 35, to: 45 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["مطلقة", "أرملة"],
      children: ["لا مانع من وجود أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "الجيزة",
      otherConditions: "تكون جادة في حياتها ومتفهمة لمسؤوليات الحياة.",
      additionalNotes: "تتقي الله وتقدر الحياة الأسرية.",
    },
  },
  {
    code: 16,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/16.jpg",
      name: "أشرف إبراهيم منصور",
      job: "مصمم جرافيك",
      description: "مبدع وأحب الفن والابتكار، ملتزم دينياً وأبحث عن الاستقرار.",
      skinColor: "قمحي",
      qualification: "بكالوريوس فنون تطبيقية",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 32,
      socialStatus: "أعزب",
      height: 170,
      location: "الشرقية",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01123467891",
    },
    brideRequirements: {
      ageRange: { from: 25, to: 30 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["أعزب"],
      children: ["بدون أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "الشرقية",
      otherConditions: "تكون متفهمة وتحب الحياة الزوجية.",
      additionalNotes: "تكون ملتزمة ومحبة للهدوء والاستقرار.",
    },
  },
  {
    code: 17,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/17.jpg",
      name: "خالد حمدي مصطفى",
      job: "محاسب مالي",
      description: "دقيق ومنظم، محب للرياضة وأهتم بالاستقرار الأسري.",
      skinColor: "أسمر",
      qualification: "بكالوريوس تجارة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 36,
      socialStatus: "أعزب",
      height: 175,
      location: "الفيوم",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01056781234",
    },
    brideRequirements: {
      ageRange: { from: 28, to: 35 },
      qualification: "مؤهل جامعي",
      maritalStatus: ["أعزب"],
      children: ["بدون أطفال"],
      housing: "إيجار جديد",
      area: "متوسطة",
      government: "الفيوم",
      otherConditions: "تتقي الله وتحب الاستقرار الأسري.",
      additionalNotes: "تكون ودودة وتحب الحياة الزوجية.",
    },
  },
  {
    code: 18,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/18.jpg",
      name: "مصطفى جمال عبدالرحيم",
      job: "فني شبكات",
      description: "مهتم بالتكنولوجيا، وأحب التطوير الدائم في عملي.",
      skinColor: "فاتح",
      qualification: "دبلوم صنايع",
      hasChildren: true,
      childrenNumber: 2,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 40,
      socialStatus: "مطلق",
      height: 178,
      location: "طنطا",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01234567897",
    },
    brideRequirements: {
      ageRange: { from: 30, to: 40 },
      qualification: "مؤهل متوسط",
      maritalStatus: ["مطلقة", "أرملة"],
      children: ["لا مانع من وجود أطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "طنطا",
      otherConditions: "تكون جادة ومستعدة لتكوين أسرة مستقرة.",
      additionalNotes: "تحب الأطفال وتهتم بالحياة الأسرية.",
    },
  },
  {
    code: 19,
    suspended: false,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/19.jpg",
      name: "علي عبدالحكيم نصر",
      job: "فني إلكترونيات",
      description: "محب للتكنولوجيا وأعمل في الصيانة منذ سنوات.",
      skinColor: "قمحي",
      qualification: "دبلوم فني",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 35,
      socialStatus: "أعزب",
      height: 172,
      location: "سوهاج",
      sameGovernment: true,
      acceptPolygamy: false,
      phone: "01112345678",
    },
    brideRequirements: {
      ageRange: { from: 28, to: 35 },
      qualification: "مؤهل متوسط أو جامعي",
      maritalStatus: ["أعزب"],
      children: ["بدون أطفال"],
      housing: "إيجار جديد",
      area: "متوسطة",
      government: "سوهاج",
      otherConditions: "تتقي الله وتحب الحياة الزوجية.",
      additionalNotes: "تكون على خلق ومستعدة لتكوين أسرة.",
    },
  },
  {
    code: 20,
    suspended: true,
    groomSpecifications: {
      img: "https://randomuser.me/api/portraits/men/20.jpg",
      name: "علاء إبراهيم سالم",
      job: "سائق نقل ثقيل",
      description: "محب للعمل وأطمح لتوسيع أعمالي الخاصة.",
      skinColor: "أسمر",
      qualification: "دبلوم صنايع",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "سليم",
      prayer: true,
      age: 39,
      socialStatus: "أعزب",
      height: 176,
      location: "أسوان",
      sameGovernment: true,
      acceptPolygamy: true,
      phone: "01234567898",
    },
    brideRequirements: {
      ageRange: { from: 30, to: 39 },
      qualification: "مؤهل متوسط أو جامعي",
      maritalStatus: ["أعزب"],
      children: ["بدون أطفال"],
      housing: "إيجار جديد",
      area: "متوسطة",
      government: "أسوان",
      otherConditions: "تتقي الله وتحب الاستقرار الأسري.",
      additionalNotes: "تكون على خلق وتقدر الحياة الزوجية.",
    },
  },
];
