export const womenFormData = [
  {
    code: 1,
    suspended: false,
    brideSpecifications: {
      name: "مريم احمد عبدالله",
      job: "طبيبة",
      description:
        "الحمد على قدر من الجمال بشوشه متواضعه لا احب النفاق ولا الكذب وعلى قدر من الالتزام والاحتشام.",
      skinColor: "بيضاء / ناصعة البياض",
      qualification: "دكتورة",
      hasChildren: true,
      childrenNumber: 3,
      illnessOrDisability: true,
      healthStatus: "مرض السكري",
      prayer: true,
      age: 35,
      socialStatus: "أرملة",
      height: 168,
      location: "الشرقية",
      sameGovernment: true,
      acceptPolygamy: true,
      polygamyConditions: "العدل بين الزوجات",
      phone: "01012345678",
    },
    groomRequirements: {
      ageRange: { from: 25, to: 30 },
      qualification: "عالي",
      maritalStatus: ["اعزب", "مطلق", "متزوج", "أرمل"],
      children: ["بدون اطفال", "الاطفال مع الزوج", "الأطفال فى حضانة والدتهم"],
      housing: "تمليك",
      area: "راقية",
      government: "الشرقية",
      otherConditions: "ان يتقى الله ومصلى وغير مدخن ومتدين.",
      additionalNotes:
        "ان يكون ذو خلق باعتراف من حولة جميعا غير عصبي ملتزم و ليس على خلاف مع اي فكر من الافكار الاخرى ملتزم بالسنة و يحب الدعوة الى الله على طريقة الرسول صلى الله عليه و سلم.",
    },
  },
  {
    code: 2,
    suspended: true,
    brideSpecifications: {
      name: "فاطمة محمد علي",
      job: "مهندسة",
      description: "على قدر من الجمال والالتزام، احب النظام والوضوح والصدق.",
      skinColor: "قمحية",
      qualification: "بكالوريوس هندسة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 30,
      socialStatus: "مطلقة",
      height: 160,
      location: "القاهرة",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01098765432",
    },
    groomRequirements: {
      ageRange: { from: 32, to: 40 },
      qualification: "عالي",
      maritalStatus: ["متزوج", "أرمل"],
      children: ["بدون اطفال"],
      housing: "ايجار",
      area: "راقية",
      government: "القاهرة",
      otherConditions: "ملتزم ومصلى، يفضل غير مدخن.",
      additionalNotes: "يكون على درجة من الالتزام والخلق وحسن التعامل.",
    },
  },
  {
    code: 3,
    suspended: false,
    brideSpecifications: {
      name: "أسماء خالد محمود",
      job: "مدرسة",
      description: "محافظة على الصلاة وملتزمة، ابحث عن زوج متدين وذو خلق.",
      skinColor: "حنطية",
      qualification: "ليسانس آداب",
      hasChildren: true,
      childrenNumber: 1,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 28,
      socialStatus: "مطلقة",
      height: 155,
      location: "المنصورة",
      sameGovernment: false,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01022334455",
    },
    groomRequirements: {
      ageRange: { from: 30, to: 35 },
      qualification: "عالي",
      maritalStatus: ["اعزب", "أرمل"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "متوسطة",
      government: "الدقهلية",
      otherConditions: "متدين وعلى قدر من الالتزام.",
      additionalNotes: "يكون شخص صادق وغير مدخن.",
    },
  },
  {
    code: 4,
    suspended: false,
    brideSpecifications: {
      name: "سعاد علي حسين",
      job: "محاسبة",
      description: "شخصية قوية ومحبة للعمل، ابحث عن زوج ذو عقلية منفتحة.",
      skinColor: "بيضاء",
      qualification: "بكالوريوس تجارة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة ممتازة",
      prayer: true,
      age: 33,
      socialStatus: "عزباء",
      height: 170,
      location: "الإسكندرية",
      sameGovernment: true,
      acceptPolygamy: true,
      polygamyConditions: "لا بأس بشرط العدل.",
      phone: "01234567891",
    },
    groomRequirements: {
      ageRange: { from: 35, to: 45 },
      qualification: "عالي",
      maritalStatus: ["متزوج", "أرمل"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "الإسكندرية",
      otherConditions: "يكون على قدر من التعليم والانفتاح.",
      additionalNotes: "يكون شخص عملي وذكي ومتفاهم.",
    },
  },
  {
    code: 5,
    suspended: false,
    brideSpecifications: {
      name: "هند سالم عبدالعزيز",
      job: "طبيبة أسنان",
      description: "هادئة الطباع وملتزمة بالفرائض الدينية، ابحث عن زوج صالح.",
      skinColor: "حنطية",
      qualification: "بكالوريوس طب",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 29,
      socialStatus: "عزباء",
      height: 165,
      location: "الجيزة",
      sameGovernment: false,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01044556677",
    },
    groomRequirements: {
      ageRange: { from: 30, to: 40 },
      qualification: "عالي",
      maritalStatus: ["اعزب", "أرمل"],
      children: ["بدون اطفال"],
      housing: "ايجار",
      area: "متوسطة",
      government: "الجيزة",
      otherConditions: "يكون ملتزم ومحترم.",
      additionalNotes: "يحب الاستقرار الأسري.",
    },
  },
  {
    code: 6,
    suspended: true,
    brideSpecifications: {
      name: "ليلى حسن إبراهيم",
      job: "محامية",
      description: "شخصية قوية وذات إرادة، ابحث عن شخص مستقل وقوي الشخصية.",
      skinColor: "سمراء",
      qualification: "بكالوريوس حقوق",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 34,
      socialStatus: "مطلقة",
      height: 160,
      location: "الشرقية",
      sameGovernment: false,
      acceptPolygamy: true,
      polygamyConditions: "العدل بين الزوجات.",
      phone: "01122334455",
    },
    groomRequirements: {
      ageRange: { from: 35, to: 45 },
      qualification: "عالي",
      maritalStatus: ["متزوج", "أرمل"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "الشرقية",
      otherConditions: "شخص متفهم ولديه طموح.",
      additionalNotes: "يكون مثقف ومتوازن في قراراته.",
    },
  },
  {
    code: 7,
    suspended: false,
    brideSpecifications: {
      name: "نادية علي محمود",
      job: "مدرسة",
      description: "محبة للعمل والتعليم، احب الصراحة والوضوح.",
      skinColor: "بيضاء",
      qualification: "بكالوريوس تربية",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة ممتازة",
      prayer: true,
      age: 26,
      socialStatus: "عزباء",
      height: 170,
      location: "القاهرة",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01099887766",
    },
    groomRequirements: {
      ageRange: { from: 28, to: 35 },
      qualification: "عالي",
      maritalStatus: ["اعزب"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "متوسطة",
      government: "القاهرة",
      otherConditions: "يكون ملتزم ومتدين.",
      additionalNotes: "يكون شخص صادق وحسن المعاملة.",
    },
  },
  {
    code: 8,
    suspended: false,
    brideSpecifications: {
      name: "أميرة سعيد فتحي",
      job: "مهندسة ديكور",
      description: "ذات ذوق رفيع ومحبة للفنون، ابحث عن شخص ذو ثقافة.",
      skinColor: "بيضاء",
      qualification: "بكالوريوس هندسة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 31,
      socialStatus: "عزباء",
      height: 160,
      location: "المنصورة",
      sameGovernment: false,
      acceptPolygamy: true,
      polygamyConditions: "العدل والمساواة.",
      phone: "01022336688",
    },
    groomRequirements: {
      ageRange: { from: 32, to: 38 },
      qualification: "عالي",
      maritalStatus: ["متزوج", "أرمل"],
      children: ["بدون اطفال"],
      housing: "ايجار",
      area: "راقية",
      government: "الدقهلية",
      otherConditions: "شخص على قدر من العلم والأدب.",
      additionalNotes: "يكون مثقفاً ومحافظاً على الأخلاق.",
    },
  },
  {
    code: 9,
    suspended: true,
    brideSpecifications: {
      name: "دعاء مصطفى حسن",
      job: "صيدلانية",
      description: "محبة للعلم، ابحث عن زوج يهتم بالتعليم والأخلاق.",
      skinColor: "حنطية",
      qualification: "بكالوريوس صيدلة",
      hasChildren: true,
      childrenNumber: 2,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 34,
      socialStatus: "أرملة",
      height: 165,
      location: "دمياط",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01055667788",
    },
    groomRequirements: {
      ageRange: { from: 35, to: 45 },
      qualification: "عالي",
      maritalStatus: ["أرمل"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "متوسطة",
      government: "دمياط",
      otherConditions: "ملتزم وعلى قدر من المسؤولية.",
      additionalNotes: "يكون شخص هادئ ويفضل العيش بأسلوب بسيط.",
    },
  },
  {
    code: 10,
    suspended: true,
    brideSpecifications: {
      name: "رنا محمود كمال",
      job: "مترجمة",
      description: "هادئة وخجولة، احب السفر والتعرف على الثقافات.",
      skinColor: "بيضاء",
      qualification: "ليسانس لغات وترجمة",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 29,
      socialStatus: "عزباء",
      height: 162,
      location: "الجيزة",
      sameGovernment: false,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01066778899",
    },
    groomRequirements: {
      ageRange: { from: 30, to: 35 },
      qualification: "عالي",
      maritalStatus: ["اعزب"],
      children: ["بدون اطفال"],
      housing: "ايجار",
      area: "متوسطة",
      government: "الجيزة",
      otherConditions: "شخص محب للعلم والثقافة.",
      additionalNotes: "يكون متفهم وعقلاني.",
    },
  },
  {
    code: 11,
    suspended: false,
    brideSpecifications: {
      name: "سارة أحمد يوسف",
      job: "مديرة تسويق",
      description: "طموحة ومحبة للعمل، ابحث عن زوج متعاون.",
      skinColor: "قمحية",
      qualification: "بكالوريوس إدارة أعمال",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة ممتازة",
      prayer: true,
      age: 33,
      socialStatus: "عزباء",
      height: 168,
      location: "القاهرة",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01088776655",
    },
    groomRequirements: {
      ageRange: { from: 35, to: 40 },
      qualification: "عالي",
      maritalStatus: ["اعزب", "مطلق"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "القاهرة",
      otherConditions: "يكون ملتزم ومحترم.",
      additionalNotes: "يكون داعماً لي في حياتي العملية.",
    },
  },
  {
    code: 12,
    suspended: false,
    brideSpecifications: {
      name: "شيماء حسين علي",
      job: "طبيبة",
      description: "ملتزمة ومحافظة، ابحث عن زوج متدين وملتزم.",
      skinColor: "حنطية",
      qualification: "بكالوريوس طب",
      hasChildren: true,
      childrenNumber: 2,
      illnessOrDisability: false,
      healthStatus: "صحة ممتازة",
      prayer: true,
      age: 36,
      socialStatus: "أرملة",
      height: 160,
      location: "الإسكندرية",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01055443322",
    },
    groomRequirements: {
      ageRange: { from: 37, to: 45 },
      qualification: "عالي",
      maritalStatus: ["أرمل", "مطلق"],
      children: ["الأطفال فى حضانة والدتهم"],
      housing: "تمليك",
      area: "متوسطة",
      government: "الإسكندرية",
      otherConditions: "ملتزم ويخاف الله.",
      additionalNotes: "يكون شخص مسؤول وقادر على إدارة الأسرة.",
    },
  },
  {
    code: 13,
    suspended: false,
    brideSpecifications: {
      name: "هالة يوسف إسماعيل",
      job: "ممرضة",
      description: "ودودة ومهتمة بالعناية بالآخرين، ابحث عن شخص طيب القلب.",
      skinColor: "بيضاء",
      qualification: "دبلوم تمريض",
      hasChildren: false,
      illnessOrDisability: true,
      healthStatus: "ضغط الدم المرتفع",
      prayer: true,
      age: 32,
      socialStatus: "عزباء",
      height: 160,
      location: "أسيوط",
      sameGovernment: false,
      acceptPolygamy: true,
      polygamyConditions: "العدل بين الزوجات.",
      phone: "01122334411",
    },
    groomRequirements: {
      ageRange: { from: 35, to: 42 },
      qualification: "متوسط",
      maritalStatus: ["أرمل", "مطلق"],
      children: ["الاطفال مع الزوج"],
      housing: "تمليك",
      area: "متوسطة",
      government: "أسيوط",
      otherConditions: "يكون شخص متفهم وصبور.",
      additionalNotes: "يكون قادر على العطاء ورعاية الأسرة.",
    },
  },
  {
    code: 14,
    suspended: true,
    brideSpecifications: {
      name: "عائشة عبد الرحمن",
      job: "ربة منزل",
      description: "محبة للأسرة والاهتمام بالأطفال، ابحث عن زوج يقدر الأسرة.",
      skinColor: "سمراء",
      qualification: "ثانوية عامة",
      hasChildren: true,
      childrenNumber: 4,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 40,
      socialStatus: "أرملة",
      height: 158,
      location: "الفيوم",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01099882244",
    },
    groomRequirements: {
      ageRange: { from: 40, to: 50 },
      qualification: "متوسط",
      maritalStatus: ["أرمل", "مطلق"],
      children: ["الاطفال مع الزوج"],
      housing: "تمليك",
      area: "متوسطة",
      government: "الفيوم",
      otherConditions: "يكون شخص يقدر الأسرة ومسؤول.",
      additionalNotes: "يكون رحيم وعادل في تعامله مع الأبناء.",
    },
  },
  {
    code: 15,
    suspended: false,
    brideSpecifications: {
      name: "هناء علي محمد",
      job: "معلمة",
      description: "مهتمة بالتعليم والتطوير، ابحث عن زوج متفهم وذو طموح.",
      skinColor: "قمحية",
      qualification: "بكالوريوس تربية",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة ممتازة",
      prayer: true,
      age: 28,
      socialStatus: "عزباء",
      height: 162,
      location: "القليوبية",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01055667799",
    },
    groomRequirements: {
      ageRange: { from: 30, to: 35 },
      qualification: "عالي",
      maritalStatus: ["اعزب"],
      children: ["بدون اطفال"],
      housing: "ايجار",
      area: "متوسطة",
      government: "القليوبية",
      otherConditions: "يكون مهتم بالتعليم والطموح.",
      additionalNotes: "يكون شخص طموح ومستعد لدعم الأسرة.",
    },
  },
  {
    code: 16,
    suspended: true,
    brideSpecifications: {
      name: "رنا كمال إبراهيم",
      job: "مستشارة قانونية",
      description: "أحب النظام والالتزام، أبحث عن شخص جاد.",
      skinColor: "بيضاء",
      qualification: "ماجستير قانون",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 30,
      socialStatus: "عزباء",
      height: 170,
      location: "الجيزة",
      sameGovernment: false,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01044556677",
    },
    groomRequirements: {
      ageRange: { from: 32, to: 37 },
      qualification: "عالي",
      maritalStatus: ["اعزب"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "الجيزة",
      otherConditions: "شخص جاد وصادق.",
      additionalNotes: "يكون نزيه وقادر على تحمل المسؤولية.",
    },
  },
  {
    code: 17,
    suspended: false,
    brideSpecifications: {
      name: "سلمى عبد الله",
      job: "مساعدة طبية",
      description: "محبة للأعمال الخيرية، أبحث عن شخص ملتزم ومهتم بالمجتمع.",
      skinColor: "بيضاء",
      qualification: "دبلوم تمريض",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 27,
      socialStatus: "عزباء",
      height: 158,
      location: "القاهرة",
      sameGovernment: true,
      acceptPolygamy: true,
      polygamyConditions: "العدل بين الزوجات.",
      phone: "01033445566",
    },
    groomRequirements: {
      ageRange: { from: 28, to: 33 },
      qualification: "عالي",
      maritalStatus: ["اعزب", "مطلق"],
      children: ["بدون اطفال"],
      housing: "ايجار",
      area: "متوسطة",
      government: "القاهرة",
      otherConditions: "يكون ملتزم بالمجتمع ويفضل العمل الخيري.",
      additionalNotes: "يكون شخص طيب القلب وصادق.",
    },
  },
  {
    code: 18,
    suspended: false,
    brideSpecifications: {
      name: "نجوى حسين",
      job: "مديرة مشاريع",
      description: "طموحة ومجتهدة، أبحث عن شريك حياة يشاركني أهدافي.",
      skinColor: "قمحية",
      qualification: "بكالوريوس إدارة أعمال",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 32,
      socialStatus: "عزباء",
      height: 165,
      location: "الشرقية",
      sameGovernment: true,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01055667700",
    },
    groomRequirements: {
      ageRange: { from: 33, to: 40 },
      qualification: "عالي",
      maritalStatus: ["اعزب", "مطلق"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "الشرقية",
      otherConditions: "يكون طموح ومجتهد.",
      additionalNotes: "يكون شريك حياة داعم ومتفهم.",
    },
  },
  {
    code: 19,
    suspended: true,
    brideSpecifications: {
      name: "زهراء محمد",
      job: "أستاذة جامعية",
      description: "محبة للعلم والتعلم، أبحث عن شخص متعلم ومهتم بالثقافة.",
      skinColor: "بيضاء",
      qualification: "دكتوراه",
      hasChildren: false,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 34,
      socialStatus: "عزباء",
      height: 170,
      location: "أسوان",
      sameGovernment: false,
      acceptPolygamy: false,
      polygamyConditions: "",
      phone: "01066778800",
    },
    groomRequirements: {
      ageRange: { from: 35, to: 40 },
      qualification: "عالي",
      maritalStatus: ["اعزب"],
      children: ["بدون اطفال"],
      housing: "تمليك",
      area: "راقية",
      government: "أسوان",
      otherConditions: "شخص مثقف ويحب العلم.",
      additionalNotes: "يكون داعماً للطموحات التعليمية.",
    },
  },
  {
    code: 20,
    suspended: false,
    brideSpecifications: {
      name: "سناء عبد الله",
      job: "مصممة أزياء",
      description: "مبدعة وذات ذوق رفيع، أبحث عن شريك يشجع إبداعي.",
      skinColor: "سمراء",
      qualification: "بكالوريوس تصميم أزياء",
      hasChildren: true,
      childrenNumber: 1,
      illnessOrDisability: false,
      healthStatus: "صحة جيدة",
      prayer: true,
      age: 29,
      socialStatus: "مطلقة",
      height: 160,
      location: "الإسكندرية",
      sameGovernment: true,
      acceptPolygamy: true,
      polygamyConditions: "العدل والاحترام.",
      phone: "01077889900",
    },
    groomRequirements: {
      ageRange: { from: 30, to: 35 },
      qualification: "عالي",
      maritalStatus: ["مطلق"],
      children: ["الأطفال فى حضانة والدتهم"],
      housing: "ايجار",
      area: "راقية",
      government: "الإسكندرية",
      otherConditions: "يكون داعماً ومشجعاً للإبداع.",
      additionalNotes: "يكون صادق ومهتم بالفن والثقافة.",
    },
  },
];
