export const womenFormData = [
  {
    code: 1,
    suspended: false,
    name: "مريم احمد عبدالله",
    job: "طبيبة",
    description:
      "الحمد على قدر من الجمال بشوشه متواضعه لا احب النفاق ولا الكذب وعلى قدر من الالتزام والاحتشام.",
    skinColor: "بيضاء / ناصعة البياض",
    qualification: "دكتورة",
    hasChildren: true,
    childrenNumber: 3,
    illnessOrDisability: true,
    healthStatus: "مرض السكري",
    prayer: true,
    age: 35,
    socialStatus: "أرملة",
    height: 168,
    governorate: "الشرقية",
    sameGovernorate: true,
    acceptPolygamy: true,
    polygamyConditions: "العدل بين الزوجات",
    acceptDivorcedWidow: true,
    phone: "01012345678",
    groomHousing: "تمليك",
    groomRegion: "راقية",
    groomQualification: "مؤهل عالي",
    groomAgeRange: { from: 25, to: 30 },
    groomMaritalStatus: ["اعزب", "مطلق", "متزوج", "أرمل"],
    groomchildren: [
      "بدون اطفال",
      "الاطفال مع الزوج",
      "الأطفال فى حضانة والدتهم",
    ],
    otherConditions: "ان يتقى الله ومصلى وغير مدخن ومتدين.",
    additionalNotes:
      "ان يكون ذو خلق باعتراف من حولة جميعا غير عصبي ملتزم و ليس على خلاف مع اي فكر من الافكار الاخرى ملتزم بالسنة و يحب الدعوة الى الله على طريقة الرسول صلى الله عليه و سلم.",
  },
  {
    code: 2,
    suspended: true,
    name: "فاطمة محمد علي",
    job: "مهندسة",
    description: "على قدر من الجمال والالتزام، احب النظام والوضوح والصدق.",
    skinColor: "قمحية",
    qualification: "مهندسة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 30,
    socialStatus: "مطلقة",
    height: 160,
    governorate: "القاهرة",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01098765432",
    groomHousing: "إيجار",
    groomRegion: "راقية",
    groomQualification: "مهندس",
    groomAgeRange: { from: 32, to: 40 },
    groomMaritalStatus: ["متزوج", "أرمل"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "ملتزم ومصلى، يفضل غير مدخن.",
    additionalNotes: "يكون على درجة من الالتزام والخلق وحسن التعامل.",
  },
  {
    code: 3,
    suspended: false,
    name: "أسماء خالد محمود",
    job: "مدرسة",
    description: "محافظة على الصلاة وملتزمة، ابحث عن زوج متدين وذو خلق.",
    skinColor: "فاتحة",
    qualification: "مؤهل عالي",
    hasChildren: true,
    childrenNumber: 1,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 28,
    socialStatus: "مطلقة",
    height: 155,
    governorate: "كفر الشيخ",
    sameGovernorate: false,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: false,
    phone: "01022334455",
    groomHousing: "تمليك",
    groomRegion: "متوسطة",
    groomQualification: "بدون مؤهل",
    groomAgeRange: { from: 30, to: 35 },
    groomMaritalStatus: ["اعزب", "أرمل"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "متدين وعلى قدر من الالتزام.",
    additionalNotes: "يكون شخص صادق وغير مدخن.",
  },
  {
    code: 4,
    suspended: false,
    name: "سعاد علي حسين",
    job: "محاسبة",
    description: "شخصية قوية ومحبة للعمل، ابحث عن زوج ذو عقلية منفتحة.",
    skinColor: "عنابية",
    qualification: "خريجة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة ممتازة",
    prayer: true,
    age: 33,
    socialStatus: "عزباء",
    height: 170,
    governorate: "الإسكندرية",
    sameGovernorate: true,
    acceptPolygamy: true,
    polygamyConditions: "لا بأس بشرط العدل.",
    acceptDivorcedWidow: true,
    phone: "01234567891",
    groomHousing: "تمليك",
    groomRegion: "راقية",
    groomQualification: "دبلوم",
    groomAgeRange: { from: 35, to: 45 },
    groomMaritalStatus: ["متزوج", "أرمل"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "يكون على قدر من التعليم والانفتاح.",
    additionalNotes: "يكون شخص عملي وذكي ومتفاهم.",
  },
  {
    code: 5,
    suspended: false,
    name: "هند سالم عبدالعزيز",
    job: "طبيبة أسنان",
    description: "هادئة الطباع وملتزمة بالفرائض الدينية، ابحث عن زوج صالح.",
    skinColor: "فاتحة",
    qualification: "دكتورة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 29,
    socialStatus: "عزباء",
    height: 165,
    governorate: "الجيزة",
    sameGovernorate: false,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01044556677",
    groomHousing: "إيجار",
    groomRegion: "متوسطة",
    groomQualification: "شهادة اعدادية",
    groomAgeRange: { from: 30, to: 40 },
    groomMaritalStatus: ["اعزب", "أرمل"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "يكون ملتزم ومحترم.",
    additionalNotes: "يحب الاستقرار الأسري.",
  },
  {
    code: 6,
    suspended: true,
    name: "ليلى حسن إبراهيم",
    job: "محامية",
    description: "شخصية قوية وذات إرادة، ابحث عن شخص مستقل وقوي الشخصية.",
    skinColor: "سمراء",
    qualification: "خريجة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 34,
    socialStatus: "مطلقة",
    height: 160,
    governorate: "الشرقية",
    sameGovernorate: false,
    acceptPolygamy: true,
    polygamyConditions: "العدل بين الزوجات.",
    acceptDivorcedWidow: true,
    phone: "01122334455",
    groomHousing: "تمليك",
    groomRegion: "راقية",
    groomQualification: "مهندس",
    groomAgeRange: { from: 35, to: 45 },
    groomMaritalStatus: ["متزوج", "أرمل"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "شخص متفهم ولديه طموح.",
    additionalNotes: "يكون مثقف ومتوازن في قراراته.",
  },
  {
    code: 7,
    suspended: false,
    name: "نادية علي محمود",
    job: "مدرسة",
    description: "محبة للعمل والتعليم، احب الصراحة والوضوح.",
    skinColor: "شقراء",
    qualification: "مؤهل عالي",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة ممتازة",
    prayer: true,
    age: 26,
    socialStatus: "عزباء",
    height: 170,
    governorate: "القاهرة",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: false,
    phone: "01099887766",
    groomHousing: "تمليك",
    groomRegion: "متوسطة",
    groomQualification: "مؤهل عالي",
    groomAgeRange: { from: 28, to: 35 },
    groomMaritalStatus: ["اعزب"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "يكون ملتزم ومتدين.",
    additionalNotes: "يكون شخص صادق وحسن المعاملة.",
  },
  {
    code: 8,
    suspended: false,
    name: "أميرة سعيد فتحي",
    job: "مهندسة ديكور",
    description: "ذات ذوق رفيع ومحبة للفنون، ابحث عن شخص ذو ثقافة.",
    skinColor: "بيضاء / ناصعة البياض",
    qualification: "مهندسة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 31,
    socialStatus: "عزباء",
    height: 160,
    governorate: "كفر الشيخ",
    sameGovernorate: false,
    acceptPolygamy: true,
    polygamyConditions: "العدل والمساواة.",
    acceptDivorcedWidow: true,
    phone: "01022336688",
    groomHousing: "إيجار",
    groomRegion: "راقية",
    groomQualification: "شهادة اعدادية",
    groomAgeRange: { from: 32, to: 38 },
    groomMaritalStatus: ["متزوج", "أرمل"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "شخص على قدر من العلم والأدب.",
    additionalNotes: "يكون مثقفاً ومحافظاً على الأخلاق.",
  },
  {
    code: 9,
    suspended: true,
    name: "دعاء مصطفى حسن",
    job: "صيدلانية",
    description: "محبة للعلم، ابحث عن زوج يهتم بالتعليم والأخلاق.",
    skinColor: "فاتحة",
    qualification: "مؤهل عالي",
    hasChildren: true,
    childrenNumber: 2,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 34,
    socialStatus: "أرملة",
    height: 165,
    governorate: "دمياط",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01055667788",
    groomHousing: "تمليك",
    groomRegion: "متوسطة",
    groomQualification: "شهادة ابتدائية",
    groomAgeRange: { from: 35, to: 45 },
    groomMaritalStatus: ["أرمل"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "ملتزم وعلى قدر من المسؤولية.",
    additionalNotes: "يكون شخص هادئ ويفضل العيش بأسلوب بسيط.",
  },
  {
    code: 10,
    suspended: true,
    name: "رنا محمود كمال",
    job: "مترجمة",
    description: "هادئة وخجولة، احب السفر والتعرف على الثقافات.",
    skinColor: "بيضاء / ناصعة البياض",
    qualification: "معلمة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 29,
    socialStatus: "عزباء",
    height: 162,
    governorate: "الجيزة",
    sameGovernorate: false,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: false,
    phone: "01066778899",
    groomHousing: "إيجار",
    groomRegion: "متوسطة",
    groomQualification: "خريج",
    groomAgeRange: { from: 30, to: 35 },
    groomMaritalStatus: ["اعزب"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "شخص محب للعلم والثقافة.",
    additionalNotes: "يكون متفهم وعقلاني.",
  },
  {
    code: 11,
    suspended: false,
    name: "سارة أحمد يوسف",
    job: "مديرة تسويق",
    description: "طموحة ومحبة للعمل، ابحث عن زوج متعاون.",
    skinColor: "قمحية",
    qualification: "دبلوم",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة ممتازة",
    prayer: true,
    age: 33,
    socialStatus: "عزباء",
    height: 168,
    governorate: "القاهرة",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01088776655",
    groomHousing: "تمليك",
    groomRegion: "راقية",
    groomQualification: "مؤهل عالي",
    groomAgeRange: { from: 35, to: 40 },
    groomMaritalStatus: ["اعزب", "مطلق"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "يكون ملتزم ومحترم.",
    additionalNotes: "يكون داعماً لي في حياتي العملية.",
  },
  {
    code: 12,
    suspended: false,
    name: "شيماء حسين علي",
    job: "طبيبة",
    description: "ملتزمة ومحافظة، ابحث عن زوج متدين وملتزم.",
    skinColor: "فاتحة",
    qualification: "دكتورة",
    hasChildren: true,
    childrenNumber: 2,
    illnessOrDisability: false,
    healthStatus: "صحة ممتازة",
    prayer: true,
    age: 36,
    socialStatus: "أرملة",
    height: 160,
    governorate: "الإسكندرية",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01055443322",
    groomHousing: "تمليك",
    groomRegion: "متوسطة",
    groomQualification: "دكتور",
    groomAgeRange: { from: 37, to: 45 },
    groomMaritalStatus: ["أرمل", "مطلق"],
    groomchildren: ["الأطفال فى حضانة والدتهم"],
    otherConditions: "ملتزم ويخاف الله.",
    additionalNotes: "يكون شخص مسؤول وقادر على إدارة الأسرة.",
  },
  {
    code: 13,
    suspended: false,
    name: "هالة يوسف إسماعيل",
    job: "ممرضة",
    description: "ودودة ومهتمة بالعناية بالآخرين، ابحث عن شخص طيب القلب.",
    skinColor: "داكنة",
    qualification: "دبلوم",
    hasChildren: false,
    illnessOrDisability: true,
    healthStatus: "ضغط الدم المرتفع",
    prayer: true,
    age: 32,
    socialStatus: "عزباء",
    height: 160,
    governorate: "أسيوط",
    sameGovernorate: false,
    acceptPolygamy: true,
    polygamyConditions: "العدل بين الزوجات.",
    acceptDivorcedWidow: false,
    phone: "01122334411",
    groomHousing: "تمليك",
    groomRegion: "شعبية",
    groomQualification: "مؤهل متوسط ( ثانوية )",
    groomAgeRange: { from: 35, to: 42 },
    groomMaritalStatus: ["أرمل", "مطلق"],
    groomchildren: ["الاطفال مع الزوج"],
    otherConditions: "يكون شخص متفهم وصبور.",
    additionalNotes: "يكون قادر على العطاء ورعاية الأسرة.",
  },
  {
    code: 14,
    suspended: true,
    name: "عائشة عبد الرحمن",
    job: "ربة منزل",
    description: "محبة للأسرة والاهتمام بالأطفال، ابحث عن زوج يقدر الأسرة.",
    skinColor: "سمراء",
    qualification: "مؤهل متوسط ( ثانوية )",
    hasChildren: true,
    childrenNumber: 4,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 40,
    socialStatus: "أرملة",
    height: 158,
    governorate: "الفيوم",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01099882244",
    groomHousing: "تمليك",
    groomRegion: "شعبية",
    groomQualification: "مؤهل متوسط ( ثانوية )",
    groomAgeRange: { from: 40, to: 50 },
    groomMaritalStatus: ["أرمل", "مطلق"],
    groomchildren: ["الاطفال مع الزوج"],
    otherConditions: "يكون شخص يقدر الأسرة ومسؤول.",
    additionalNotes: "يكون رحيم وعادل في تعامله مع الأبناء.",
  },
  {
    code: 15,
    suspended: false,
    name: "هناء علي محمد",
    job: "معلمة",
    description: "مهتمة بالتعليم والتطوير، ابحث عن زوج متفهم وذو طموح.",
    skinColor: "قمحية",
    qualification: "معلمة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة ممتازة",
    prayer: true,
    age: 28,
    socialStatus: "عزباء",
    height: 162,
    governorate: "القليوبية",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01055667799",
    groomHousing: "إيجار",
    groomRegion: "متوسطة",
    groomQualification: "شهادة ابتدائية",
    groomAgeRange: { from: 30, to: 35 },
    groomMaritalStatus: ["اعزب"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "يكون مهتم بالتعليم والطموح.",
    additionalNotes: "يكون شخص طموح ومستعد لدعم الأسرة.",
  },
  {
    code: 16,
    suspended: true,
    name: "رنا كمال إبراهيم",
    job: "مستشارة قانونية",
    description: "أحب النظام والالتزام، أبحث عن شخص جاد.",
    skinColor: "داكنة",
    qualification: "مؤهل متوسط ( ثانوية )",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 30,
    socialStatus: "عزباء",
    height: 170,
    governorate: "الجيزة",
    sameGovernorate: false,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: false,
    phone: "01044556677",
    groomHousing: "تمليك",
    groomRegion: "شعبية",
    groomQualification: "دبلوم",
    groomAgeRange: { from: 32, to: 37 },
    groomMaritalStatus: ["اعزب"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "شخص جاد وصادق.",
    additionalNotes: "يكون نزيه وقادر على تحمل المسؤولية.",
  },
  {
    code: 17,
    suspended: false,
    name: "سلمى عبد الله",
    job: "مساعدة طبية",
    description: "محبة للأعمال الخيرية، أبحث عن شخص ملتزم ومهتم بالمجتمع.",
    skinColor: "داكنة",
    qualification: "شهادة اعدادية",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 27,
    socialStatus: "عزباء",
    height: 158,
    governorate: "القاهرة",
    sameGovernorate: true,
    acceptPolygamy: true,
    polygamyConditions: "العدل بين الزوجات.",
    acceptDivorcedWidow: false,
    phone: "01033445566",
    groomHousing: "إيجار",
    groomRegion: "متوسطة",
    groomQualification: "مهندس",
    groomAgeRange: { from: 28, to: 33 },
    groomMaritalStatus: ["اعزب", "مطلق"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "يكون ملتزم بالمجتمع ويفضل العمل الخيري.",
    additionalNotes: "يكون شخص طيب القلب وصادق.",
  },
  {
    code: 18,
    suspended: false,
    name: "نجوى حسين",
    job: "مديرة مشاريع",
    description: "طموحة ومجتهدة، أبحث عن شريك حياة يشاركني أهدافي.",
    skinColor: "قمحية",
    qualification: "بدون مؤهل",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 32,
    socialStatus: "عزباء",
    height: 165,
    governorate: "الشرقية",
    sameGovernorate: true,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: true,
    phone: "01055667700",
    groomHousing: "تمليك",
    groomRegion: "شعبية",
    groomQualification: "معلم",
    groomAgeRange: { from: 33, to: 40 },
    groomMaritalStatus: ["اعزب", "مطلق"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "يكون طموح ومجتهد.",
    additionalNotes: "يكون شريك حياة داعم ومتفهم.",
  },
  {
    code: 19,
    suspended: true,
    name: "زهراء محمد",
    job: "أستاذة جامعية",
    description: "محبة للعلم والتعلم، أبحث عن شخص متعلم ومهتم بالثقافة.",
    skinColor: "داكنة",
    qualification: "دكتورة",
    hasChildren: false,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 34,
    socialStatus: "عزباء",
    height: 170,
    governorate: "أسوان",
    sameGovernorate: false,
    acceptPolygamy: false,
    polygamyConditions: "",
    acceptDivorcedWidow: false,
    phone: "01066778800",
    groomHousing: "تمليك",
    groomRegion: "راقية",
    groomQualification: "بدون مؤهل",
    groomAgeRange: { from: 35, to: 40 },
    groomMaritalStatus: ["اعزب"],
    groomchildren: ["بدون اطفال"],
    otherConditions: "شخص مثقف ويحب العلم.",
    additionalNotes: "يكون داعماً للطموحات التعليمية.",
  },
  {
    code: 20,
    suspended: false,
    name: "سناء عبدالله",
    job: "مصممة أزياء",
    description: "مبدعة وذات ذوق رفيع، أبحث عن شريك يشجع إبداعي.",
    skinColor: "سمراء",
    qualification: "شهادة ابتدائية",
    hasChildren: true,
    childrenNumber: 1,
    illnessOrDisability: false,
    healthStatus: "صحة جيدة",
    prayer: true,
    age: 29,
    socialStatus: "مطلقة",
    height: 160,
    governorate: "الإسكندرية",
    sameGovernorate: true,
    acceptPolygamy: true,
    polygamyConditions: "العدل والاحترام.",
    acceptDivorcedWidow: true,
    phone: "01077889900",
    groomHousing: "إيجار",
    groomRegion: "راقية",
    groomQualification: "دكتور",
    groomAgeRange: { from: 30, to: 35 },
    groomMaritalStatus: ["مطلق"],
    groomchildren: ["الأطفال فى حضانة والدتهم"],
    otherConditions: "يكون داعماً ومشجعاً للإبداع.",
    additionalNotes: "يكون صادق ومهتم بالفن والثقافة.",
  },
];
